### ISSUE TITLE
Documentación - Puerto Limpio - Veracruz

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#1]
Apoyar en la creación del readme.md.

**Comment by BrendaVielmas** [comment]
@knlopenknowledge  He realizado este issue para la creación del readme ya que el proyecto no cuenta con él. ¿Está bien formulado? https://github.com/AyuntamientoVeracruz/App-Puerto-Limpio/issues/5

**Comment by knlopenknowledge** [comment]
Gracias @BrendaVielmas por el aviso del issue, mi único comentario es que no olviden que la sección de la licencia es también parte de issue de licenciamiento que es otro issue aparte.

**Comment by knlopenknowledge** [comment]
Hola @BrendaVielmas  @TeresaFlores , después de una conversación con Teresa dejo por aquí también que se acuerden de avisarnos sobre los pull requests que generen para pode apoyarlas en que los equipos los revisen pronto. Gracias!!

**Comment by TeresaFlores** [comment]
@knlopenknowledge  Buen día , he realizado es te PR con los detalles del pull request que se realizo sobre la sugerencia de Readme, aquí detallo los puntos que faltan para completar el Redme.  
Documentación-Puerto Limpio #9

**Comment by TeresaFlores** [comment]
@knlopenknowledge Anteriormente habíamos   realizado @BrendaVielmas estos issues para Licenciamiento y Evaluación Técnica respectivamente. 
https://github.com/AyuntamientoVeracruz/App-Puerto-Limpio/issues/6
https://github.com/AyuntamientoVeracruz/App-Puerto-Limpio/issues/7

**Comment by knlopenknowledge** [comment]
Muchas gracias por el trabajo realizados chicas estoy cerrando este issue ya que queda en manos del equipo y de nosotros que se acepten sus contribuciones.
