### ISSUE TITLE
Blog en Abierto al público - A Tu Servicio - DataUy

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#10]
- Apoyar en creación de blog de la herramienta para Abierto al público.

**Comment by LauraPaonessa** [comment]
Muchas gracias @MaricruzJ por todo el trabajo. Cerramos este issue y vamos a continuar trabajando en el Blog internamente con Michelle. Gracias!!
