### ISSUE TITLE
Blog en Abierto al público - Derechos de Estudiantes - DataUy

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#13]
- Apoyar en creación de blog de la herramienta para Abierto al público.

**Comment by yamiquispe** [comment]
Documento de preguntas del blog en Abierto al Público:
https://docs.google.com/document/d/1n8EpF6pW8HMOphHX2WiHJhUbp0mwJPsctu6q6QtBm9g/edit
 @knlopenknowledge , @LauraPaonessa , @micmars Adjunto el documento de preguntas que envié a los señores de Data Uruguay para obtener información más exhaustiva para generar contenido en el blog de Abierto al Público. Espero desde ya su respectivo feedback a fin de agregar más preguntas y/o corregir las ya planteadas.

**Comment by LauraPaonessa** [comment]
@yamiquispe Muchas gracias por el update Yami. Las respuestas que brindó el equipo de DataUy las pueden editar para ir elaborando la vitrina según el formato que usamos. 
Las preguntas para el Blog están ok. Gracias!

**Comment by yamiquispe** [comment]
@LauraPaonessa Las respuestas que brindó el equipo de Data Uruguay ya han sido editadas y corresponden a este documento (lo compartí en el issue Elaboración de la vitrina): 
https://docs.google.com/document/d/1j7NjqZLCerVWN_7UUzBP5wer9krieDEnKtWVLx2TgW8/edit
Lo que sí faltaría editar serían las respuestas a las preguntas planteadas para la elaboración del blog Abierto al Público, pero aún estoy a la espera de esas respuestas. En cuanto las reciba, las editaré y las compartiré aquí mismo. Y, ¡Muchas gracias por el feedback!

**Comment by LauraPaonessa** [comment]
@yamiquispe Yami muchas gracias por el update. Como conversamos en la última reunión vamos a construir los Blogs, uniendo el relato de las herramientas por socios. De esta forma evitamos repetir la información y queda mejor estructurado. Gracias!

**Comment by yamiquispe** [comment]
Se ha actualizado el documento con las respuestas brindadas por parte del equipo de Data Uruguay a las preguntas planteadas para la elaboración del del blog de la herramienta Derecho de Estudiantes. 
Adjunto el enlace del documento actualizado: https://docs.google.com/document/d/12E5Yf2Vz9uQ0wD9gPFwY49ck90nCwg4r2kVd8BxFdhw/edit?usp=sharing

Observación: Aún estamos en coordinaciones con el equipo de Data Uruguay acerca de algunas respuestas que aún no satisfacen el enfoque de las preguntas planteadas.

Si tuviera alguna observación acerca de las preguntas y/o sugerencia para añadir alguna otra pregunta, por favor sírvase a comentarlo.

**Comment by LauraPaonessa** [comment]
Muchas gracias @yamiroot por todo el trabajo. Tenemos ya acceso a los documentos actualizados. 
Seguimos trabajando con esa base, teniendo en cuenta las observaciones que has dejado en el doc. Cierro entonces el issue. Gracias!
