### ISSUE TITLE
Vitrina en code.iadb.org - Derechos de Estudiantes - DataUy

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#14]
- Iniciar creación de vitrina de la herramienta para catálogo code.iadb.org.

- Coordinar luego de haber realizado la vitrina con el equipo encargado de comunicaciones.

- Hacer preguntas de follow up para blog.
Revisar Plantilla para generar contenidos en el onboarding.

**Comment by yamiquispe** [comment]
Documento: 
https://docs.google.com/document/d/1j7NjqZLCerVWN_7UUzBP5wer9krieDEnKtWVLx2TgW8/edit

mmarshall@iadb.org y code@iadb.org adjunto el contenido para la elaboración de la vitrina Derecho de estudiantes.

**Comment by knlopenknowledge** [comment]
gracias @yamiquispe aviso a @LauraPaonessa y @micmars con su apoyo en el acompañamiento de la edición de la vitrina.
cc. @JenniferHuertas @ChayoVS pueden revisar la vitrina como contenido de apoyo para la descripción que irá en el readme.md del repo.

**Comment by LauraPaonessa** [comment]
Muchas gracias @yamiquispe por la actualización. Está muy bien todo lo que han avanzado! 
Solicité permisos para poder editar el documento. Voy a dejar comentarios en el mismo para que puedan continuar trabajando. Gracias!

**Comment by yamiquispe** [comment]
@LauraPaonessa ya accedí a los permisos solicitados del documento. ¡Gracias por el feedback!

**Comment by yamiquispe** [comment]
A modo de actualización, adjunto **todos** los documentos creados para la **elaboración del contenido de la vitrina Derechos de Estudiantes**:

- **Preguntas** planteadas para la elaboración del contenido de la vitrina Derechos de Estudiantes y **respuestas** brindadas a las mismas por parte de Data Uruguay: https://docs.google.com/document/d/1n8EpF6pW8HMOphHX2WiHJhUbp0mwJPsctu6q6QtBm9g/edit?usp=sharing
- **Contenido** para la vitrina Derechos de Estudiantes (**Síntesis** de las respuestas brindadas por parte de Data Uruguay e información de la herramienta expuesta en su sitio web):  https://docs.google.com/document/d/1j7NjqZLCerVWN_7UUzBP5wer9krieDEnKtWVLx2TgW8/edit?usp=sharing

**N° total de documentos:** 2

**Link de la herramienta Derechos de Estudiantes:** https://derechosdeestudiantes.edu.uy/
**Link del repositorio de la herramienta Derechos de Estudiantes** (enlace brindado en el sitio web de la herramienta, sección "Sobre el proyecto", apartado "Disponibilidad del código como software libre "): https://github.com/datauy/DerechosDeEstudiantes-2

**Comment by LauraPaonessa** [comment]
@yamiroot muchísimas gracias por compilar toda la información y por tan claro detalle de dónde encontrar cada contenido. 
Hemos revisado con @micmars la vitrina y está ok para continuar con su publicación. Gracias nuevamente por todo tu aporte!
