### ISSUE TITLE
Evaluación técnica - Elijo Estudiar - DataUy

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#15]
Sugerir uso de servicio CI y generar reportes de calidad de código.

**Comment by pamelazoe** [comment]
Se ha generado el [issue](https://github.com/datauy/ElijoEstudiar/issues/103) correspondiente a esta tarea, quedamos en espera de feedback. !Gracias!

**Comment by knlopenknowledge** [comment]
Muchas gracias por todo el trabajo, cierro este issue porque los cambios ya fueron realizados.
