### ISSUE TITLE
Documentación - Elijo Estudiar - DataUy

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#16]
Revisar el readme.md y ver de mejorarlo.

**Comment by pamelazoe** [comment]
Se ha creado un [issue](https://github.com/datauy/ElijoEstudiar/issues/102) en el repositorio oficial con los puntos a mejorar en el readme.md

**Comment by knlopenknowledge** [comment]
Gracias @pamelazoe por los avances, aquí les dejamos unos comentarios.
- Pueden cambiar el título del issue, el encabezado debe ir dentro del texto de issue, de esa forma quedas mencionadas las cuentas de github.

**Este issue forma parte de un procesos de revisión de la piloto @BID-COMUNIDADES/laboratoria-code-squads de la iniciativa Código para el desarrollo de @EL-BID.**

Pueden poner un título como: Revisión de readme.md.

**Comment by knlopenknowledge** [comment]
Hola @pamelazoe  @Crusiris , nos dan un update de este issue? han pensado en realizar un pull request al readme? si es así, nos avisan para apoyarlas en que su Pull request sea revisado por los equipos. Nos cuentan por aquí o por slack de cualquier duda. gracias!

**Comment by pamelazoe** [comment]
Hola @knlopenknowledge, enviamos un correo al contacto del repo con la notificación de que agregamos el issue, pero hasta ahora no hemos recibido respuesta ni comentarios. De cualquier manera seguimos trabajando para agregar los datos faltantes y completar la documentación. ¡Gracias!

**Comment by pamelazoe** [comment]
Se ha generado un [PR](https://github.com/datauy/ElijoEstudiar/pull/104) en referencia a este issue. Quedamos en espera de feedback.

**Comment by knlopenknowledge** [comment]
Muchas gracias por todo el trabajo, cierro este issue :)
