### ISSUE TITLE
Vitrina en code.iadb.org - Elijo Estudiar - DataUy

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#17]
- Iniciar creación de vitrina de la herramienta para catálogo code.iadb.org.

- Coordinar luego de haber realizado la vitrina con el equipo encargado de comunicaciones.

- Hacer preguntas de follow up para blog.
Revisar Plantilla para generar contenidos en el onboarding.

**Comment by GeryMolina** [comment]
Documento con respuesta de Elijo Estudiar
https://docs.google.com/document/d/1Xo9iMS1bhvZvpITeTd0NOLTkanHeytt74hvYzEgPGjk/edit

**Comment by GeryMolina** [comment]
Contenido ya editado, a espera de corrección de @LauraPaonessa y @micmars

**Comment by LauraPaonessa** [comment]
Muchas gracias @GeryMolina Muy bien que hayan recopilado la información y la hayan editado para armar la vitrina. Dejé algunos comentarios en el texto. Seguimos avanzando!

**Comment by GeryMolina** [comment]
Listo @LauraPaonessa  ya modifiqué lo solicitado, quedo a espera de nuevas instrucciones.

**Comment by LauraPaonessa** [comment]
Muchas gracias @GeryMolina - Sugiero que al armar el Blog volvamos a revisar los contenidos de la vitrina para ver si falta sumar, aclarar o sacar alguna información. Gracias!

**Comment by LauraPaonessa** [comment]
@GeryMolina muchas gracias por la colaboración para reunir la información y armar la vitrina. Cierro este issue porque la tarea fue completada. Gracias!!
