### ISSUE TITLE
Blog en Abierto al público - Elijo Estudiar Data Uy

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#18]
Apoyar en creación de blog de la herramienta para Abierto al público.

**Comment by LauraPaonessa** [comment]
Sumo aquí el link al documento donde han trabajado este issue https://docs.google.com/document/d/1Xo9iMS1bhvZvpITeTd0NOLTkanHeytt74hvYzEgPGjk/edit#heading=h.hj4xdydbjl5a

gracias @GeryMolina por el trabajo para compilar la información y armar la vitrina!

**Comment by LauraPaonessa** [comment]
@GeryMolina Muchas gracias por gestionar esta tarea, tanto para identificar las preguntas y compilar la info. Seguiremos trabajando para armar el blogpost con la base que armaste. Gracias!
