### ISSUE TITLE
Documentación - Leyes Abiertas - Dem. en Red

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#21]
Existe pero puede mejorarse

**Comment by knlopenknowledge** [comment]
Hola @irenemonzon @mishelpa , no dan un update de este issue? colgaron algún issue en el repo oficial en la herramienta? si fue así, nos dejan el url para dejar documentado tu avance. Cualquier consulta nos cuentan por aquí o por slack. gracias!

**Comment by irenemonzon** [comment]
hola @knlopenknowledge  si  con @mishelpa  colgamos el issue en [https://github.com/DemocraciaEnRed/leyesabiertas-web/issues/109](url). forkeamos el repositorio de la herramienta,  para avanzar en el Readme y luego hacer un Pull request

**Comment by mishelpa** [comment]
Creamos un repositorio aparte en donde estamos editando un readme de documentación con algunos datos que tenemos.

El link del respositorio es https://github.com/mishelpa/readme

**Comment by mishelpa** [comment]
- [x]  Revisión del README.

- [x] Identificar los puntos de mejora.

Puntos de Mejora

- [x] **Descripción y contexto:** Descripción de las funcionalidades, el contexto donde fue desarrollado y los problemas de desarrollo que ayudó a resolver.

- [x] **Guía de usuario:** Paso a paso dirigido al usuario final sobre cómo empezar a usar la herramienta digital.

- [ ] **Guía de instalación:** Instrucciones de instalación para reutilizar y configurar la herramienta digital. (En proceso).

- [x] **Autores** Sección para dar créditos a los colaboradores de la herramienta.

- [ ] **Licencia para el código de la herramienta:** Permisos que se otorgan a terceros para reutilizar la herramienta digital.  https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

- [ ] **Licencia para la documentación de la herramienta:** Recomendamos el uso de las licencias creative commons para el licenciamiento de la documentación de las herramientas.

- [ ] **Cómo contribuir** Sección que explica a nuevos desarrolladores el proceso para contribuir a proyectos.

- [ ] **Código de conducta** El código de conducta establece las normas sociales, reglas y responsabilidades que los individuos y organizaciones deben seguir al interactuar de alguna manera con la herramienta digital o su comunidad. Es una buena práctica para crear un ambiente de respeto e inclusión en las contribuciones al proyecto. La plataforma Github premia y ayuda a los repositorios dispongan de este archivo. Al crear CODE_OF_CONDUCT.md puedes empezar desde una plantilla sugerida por ellos. 

- [ ] **Insignias (badges)** Las insignias (badges) pequeñas imágenes incrustadas en el README.md que especifican de una manera legible y concisa el estado de la herramienta. Existen insignias para el estado de desarrollo, el número de descargas, el versionado, sociales u otras. En este link podrás encontrar información https://shields.io/

- [ ] **Versión** Indica un listado de las versiones de las herramientas digital y las funcionalidades añadidas a cada versión.

**Comment by mishelpa** [comment]
Hicimos un pull request de nuestra propuesta de README y ya le hicieron el merge en el siguiente link
https://github.com/DemocraciaEnRed/leyesabiertas

**Comment by knlopenknowledge** [comment]
Excelente trabajo, mil gracias por el update, estoy cerrando el issue.
