### ISSUE TITLE
Blog Abierto al Público - Leyes Abiertas - Dem. en Red

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#22]
coordinar esto por correo electrónico con los encargados

**Comment by LauraPaonessa** [comment]
Muchas gracias @LauraMayaR y equipo por la dedicación para compilar la info sobre esta herramienta. Esa base nos va a servir para continuar elaborando el blogpost. Gracias!
