### ISSUE TITLE
Vitrina en code.iadb.org - Leyes Abiertas - Dem. en Red

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#23]
Existe, pero se puede mejorar.
https://code.iadb.org/es/herramientas/elaboracion-colaborativa-de-normas

**Comment by LauraPaonessa** [comment]
@mishelpa y equipo, les consulto en qué archivo están trabajando los contenidos de la vitrina. Si pueden compartirlo aquí para darles feedback. Mil gracias!

**Comment by LauraMayaR** [comment]
> @mishelpa y equipo, les consulto en qué archivo están trabajando los contenidos de la vitrina. Si pueden compartirlo aquí para darles feedback. Mil gracias!

Hola @LauraPaonessa Claro! este es link al documento: https://docs.google.com/document/d/1h3mAuegGWpOj3c94qLBilTpKKo0VFBWkGxYJHx2d9do/edit?usp=sharing

Gracias y saludos!

**Comment by LauraPaonessa** [comment]
Gracias @LauraMayaR por todo el trabajo y dedicación para generar el texto de la vitrina. Quedó mejor que el modelo! Procedo a cerrar el issue. Gracias!
