### ISSUE TITLE
Evaluación técnica - Presupuesto Participativo - Dem. en Red

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#24]
- Agregar badge de imagen de docker en el repo.
- Generar reportes de calidad de código.

**Comment by mariaPazBeltran** [comment]
hola, tengo una consulta, pregunte a los encargados si contaban con algún servicio de evaluación de código y dijeron que no, pero expresaron que a futuro podrían contar con uno.
Se les recomendó el uso de SonarCloud y quedaron de considerarlo. 
Ahora mi duda es: ¿igual tengo que levantar un issue para ellos sobre la evaluación técnica?, y si es así, ya que no puedo realizar el reporte ¿el issue debería tener la recomendación de uso de una herramienta de evaluación de código?

**Comment by mariaPazBeltran** [comment]
Se genero este [issue](https://github.com/DemocraciaEnRed/vicentelopez/issues/372#issue-622647021) para la evaluacion tecnica.

**Comment by knlopenknowledge** [comment]
Muchas gracias chicas por todo el trabajo, cierro el issue ya que los repos fueron actualizados gracias a sus contribuciones.
