### ISSUE TITLE
Documentación - Presupuesto Participativo - Dem. en Red

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#25]
Existe pero puede mejorarse.

**Comment by knlopenknowledge** [comment]
Hola @mariaPazBeltran , no das un update de este issue? colgaste algún issue en el repo oficial en la herramienta? si fue así nos dejar el url para dejar documentado tu avance? Cualquier consulta nos cuentas por aquí o por slack.

**Comment by mariaPazBeltran** [comment]
hola, aun no hago el issue en el repo oficial porque quería asegurarme de algunas cosas con los chicos de 'Democracia en red'.
Pero les dejo una lista de lo que he hecho y les aviso apenas haga el issue.

-  seguí la guía de instalación.
-  investigué la herramienta.
- Me comunique con los encargados de la herramienta para definir que cosas eran factibles para mejorar la documentación.
- Estoy definiendo una lista de mejoras acorde a lo conversado con los encargados.

**Comment by mariaPazBeltran** [comment]
Hola, he creado este [issue de Documentación](https://github.com/DemocraciaEnRed/vicentelopez/issues/371#issue-620464274) en el repo oficial de la herramienta. Por favor diganme si hay algo que corregir.

**Comment by Veronidas** [comment]
En el[ issue de Documentación](https://github.com/DemocraciaEnRed/vicentelopez/issues/371#issue-620464274) de Democracia en Red se hizo la traducción de parte del readme y se espera su revisión.

**Comment by knlopenknowledge** [comment]
Muchas gracias chicas por todo el trabajo, cierro el issue ya que los repos fueron actualizados gracias a sus contribuciones.
