### ISSUE TITLE
Blog en Abierto al Público - Presupuesto Participativo - Dem. en Red

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#26]
coordinar esto por correo electrónico con los encargados.

**Comment by Veronidas** [comment]
Checklist:

- [X] Lectura del material existente
- [X] Contacto vía mail.
- [X] Envió Preguntas
- [ ] Redactar 1er borrador
- [ ] Revisión 1er borrador
- [ ] Aplicar correcciones

**Comment by LauraPaonessa** [comment]
@Veronidas Muchas gracias por compilar y ordenar toda la información para organizar el blog de esta herramienta. Gracias por el punteo tan claro de los próximos pasos a seguir! Nos quedamos nosotras con la tarea de completarlos. Gracias!
