### ISSUE TITLE
Vitrina en code.iadb.org - Presupuesto Participativo - Dem. en Red

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#27]
Existe, pero se puede mejorar. https://code.iadb.org/es/herramientas/presupuestos-participativos

**Comment by Veronidas** [comment]
TO DOS:

- [X] Lectura del material existente
- [X] Contacto via mail.
- [X] Envio Preguntas
- [ ] Redactar 1er borrador
- [ ] Revisión 1er borrador
- [ ] Aplicar correcciones

**Comment by LauraPaonessa** [comment]
@Veronidas y equipo, les consulto en qué archivo están trabajando los textos de las vitrinas, si pueden compartirlo por aquí. Mil gracias!

**Comment by Veronidas** [comment]
Link al borrador de la vitrina de Presupuesto Participativo: https://docs.google.com/document/d/1_5EyvYhQm3Ym_3UI-OrEh6-gtQIyosHzLbqlBxGuohM/edit?usp=sharing

**Comment by LauraPaonessa** [comment]
Muchas gracias @Veronidas por todo el trabajo para compilar y procesar la información. La vitrina quedó muy buena. Procedo a cerrar este issue. Gracias!
