### ISSUE TITLE
Vitrina en code.iadb.org - Consultas Digitales - Dem. en Red

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#29]
Existe, pero se puede mejorar.
https://code.iadb.org/es/herramientas/consultas-digitales

**Comment by LauraPaonessa** [comment]
@Les9616 y equipo, les consulto en qué archivo están trabajando estos contenidos, si pueden compartirlo por aquí por favor. Mil gracias!

**Comment by Les9616** [comment]
https://docs.google.com/document/d/1AJ2XOo-ZTPBwqbKEDaJ47UoFa406XzV0X4oydigCWAo/edit?usp=sharing
@LauraPaonessa este es el archivo con las respuestas del equipo de Democracia en Red y la edición de la vitrina. Espero el feedback!

**Comment by LauraPaonessa** [comment]
Excelente trabajo @Les9616 ya hemos publicado la herramienta! Gracias por toda tu colaboración!
