### ISSUE TITLE
Blog Abierto al Público - Brecha Catastral y Comercial - BID

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#30]
coordinar esto por correo electrónico con los encargados

**Comment by Eli0809** [comment]
Hola @LauraPaonessa  envió el link de mis ideas para el blog https://docs.google.com/document/d/12v16womm4uELWWX02poKH3USGyijjLmogue7W-Kuxbc/edit?usp=sharing

**Comment by LauraPaonessa** [comment]
Muchas gracias @Eli0809 por organizar la información para el Blog. Lo seguimos desde ahi!
