### ISSUE TITLE
Vitrina en code.iadb.org - Recolección de Datos Inmobiliarios - BID

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#32]
Existe, pero se puede mejorar.
https://code.iadb.org/es/herramientas/recoleccion-de-datos-inmobiliarios

**Comment by Eli0809** [comment]
Form de preguntas https://docs.google.com/forms/d/e/1FAIpQLSdoZq9OKRvMg9IFqNJXCNaOrWSxOOBOY-gvZMhzQYMHI-_TNA/viewform?usp=sf_link 
Respuestas:
https://docs.google.com/spreadsheets/d/11rlkxd0quw2WdYAYXNLzaV_x8ODyBvCPwAlCelvpojI/edit?usp=sharing

**Comment by Eli0809** [comment]
Propuesta para cambios en la vitrina: https://docs.google.com/presentation/d/1PzdZtAioRhO82HgvAWOW8sX5M0SPFx2au2mcd7TZA3A/edit?usp=sharing

**Comment by LauraPaonessa** [comment]
Gracias @Eli0809 por el link. He solicitado acceso para poder darles feedback. Gracias!

**Comment by Eli0809** [comment]
Ya tienes acceso @LauraPaonessa. Espero el feedback. Gracias!

**Comment by LauraPaonessa** [comment]
Muchas gracias @Eli0809 por todo el trabajo! Cierro el issue.
