### ISSUE TITLE
Vitrina en code.iadb.org

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#5]
Iniciar creación de vitrina de la herramienta para catálogo code.iadb.org.

Coordinar luego de haber realizado la vitrina con el equipo encargado de comunicaciones. 
- Hacer preguntas de follow up para blog.
- Revisar Plantilla para generar contenidos en el onboarding.

**Comment by LauraPaonessa** [comment]
@marielysis Muchas gracias por la dedicación a realizar la vitrina aún con los inconvenientes que has tenido con tu ordenador. La vitrina está completa por lo que procedo a cerrar este issue. Gracias!
