### ISSUE TITLE
Documentación - A tu servicio -  DataUy

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#8]
Revisar el readme.md y ver de mejorarlo.

**Comment by mariajosegomezcampos** [comment]
hola creamos nuestro issues en https://github.com/datauy/ATuServicio/issues/68

**Comment by knlopenknowledge** [comment]
Gracias @mariajosegomezcampos por el aviso. Aquí te dejo nuestros comentarios:

- Pueden cambiar el título del issue, el encabezado debe ir dentro del texto de issue, de esa forma quedan mencionadas las cuentas de github.

**Este issue forma parte de un procesos de revisión de la piloto @BID-COMUNIDADES/laboratoria-code-squads de la iniciativa Código para el desarrollo de @EL-BID.**

Pueden poner un título como: **Revisión de readme.md**

**Comment by mariajosegomezcampos** [comment]
Muchas gracias por las recomendaciones, para mi son muy valiosas.

Ya hice los cambios sugeridos.

Saludos

**Comment by knlopenknowledge** [comment]
Hola @mariajosegomezcampos  @naty4393 , nos dan un update de este issue? han pensado en realizar un pull request al readme? si es así, nos avisan para apoyarlas en que su Pull request sea revisado por los equipos o en todo caso nos comentan. Nos cuentan por aquí o por slack de cualquier duda. gracias!

**Comment by mariajosegomezcampos** [comment]
hola @knlopenknowledge  estoy realizando el readme para realizar pull request.

**Comment by mariajosegomezcampos** [comment]
@knlopenknowledge  y @LauraPaonessa  realizo cambios sugeridos y pull request .

**Comment by knlopenknowledge** [comment]
Muchas gracias @mariajosegomezcampos y equipo, procedo a cerrar este issue.
