### ISSUE TITLE
Vitrina en code.iadb.org - A tu servicio - DataUy

### ISSUE THREAD

**Issue by knlopenknowledge** [BID-COMUNIDADES/Onboarding-Code-squads-Laboratoria#9]
- Iniciar creación de vitrina de la herramienta para catálogo code.iadb.org.

- Coordinar luego de haber realizado la vitrina con el equipo encargado de comunicaciones.

- Hacer preguntas de follow up para blog.
Revisar Plantilla para generar contenidos en el onboarding.

**Comment by MaricruzJ** [comment]
@micmars @LauraPaonessa @knlopenknowledge adjunto el link al documento para la generación de contenido.

https://docs.google.com/document/d/1UM6gYbSMo_uwMCAm5fvzNown8iuLl2JUxvA_jqro_Go/edit?usp=sharing

**Comment by LauraPaonessa** [comment]
Muchas gracias @MaricruzJ por el documento. Ahí dejé un comentario para poder identificarlo más fácilmente.

**Comment by LauraPaonessa** [comment]
Muchas gracias @MaricruzJ y equipo por todo el trabajo. 
Vamos a chequear con el equipo de Data un dato que mencionan en el texto. 
Les pido que nos otorguen permisos de editores, actualmente tenemos solo permiso para sugerir. 
Resolviendo estas dos cuestiones estamos listos para cerrar este issue. 
Gracias!!

**Comment by MaricruzJ** [comment]
Gracias a ustedes @LauraPaonessa, @micmars  ya esá el permiso para editar. Estaré pendiente si surge alguna duda o sugerencia.

**Comment by LauraPaonessa** [comment]
Muchas gracias @MaricruzJ por todo el trabajo para compilar la info y organizar la vitrina. Ya hemos chequeado con el equipo la info que faltaba. Procedo a cerrar este issue. Gracias!
